DROP TABLE IF EXISTS cars;

CREATE TABLE cars (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  make VARCHAR(256) NOT NULL,
  model VARCHAR(256) NOT NULL,
  colour VARCHAR(256) NOT NULL,
  year INT NOT NULL
);